server:
  port: 8080 
  
camel:
  springboot:
    name: AccountAPI
  servlet:
    mapping:
      context-path: /*
  rest:
    context-path: /
    
# =============================================
# Environment variables
# ---------------------------------------------
mockUrl:
  host: ${ACCOUNTS_URL}
  contextPath: ${ACCOUNTS_CONTEXTPATH}